

def test_something():
    raise Exception()
    assert 1 + 1 == 3